#!/usr/bin/env ruby -I./lib
#
# Watch a bestbuy API endpoint for a match on a particular JSON key.

require "site_watcher"

SiteWatcher.watch(:sleep => 1) do
  page("http://www.bestbuy.com/api/1.0/product/summaries?skus=7522006") do
    test do
      json.at(0, "availability", "ship", "displayMessage").excludes(/not available/i)
    end

    fulfilled do
      # Send email or whatever
    end
  end
end
